=== SanchezMarioo/1-DAM/Lenguajes de Marcas/XML/XSD/Ejer10.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Libro">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Titulo" type="xs:string"/>
        <xs:element ref="Contenido"/>
        <xs:element name="Copyright" type="xs:string" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Contenido">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Capitulo" maxOccurs="unbounded"/>
        <xs:element ref="Separacion" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Capitulo">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Tema" type="xs:string"/>
        <xs:element name="Seccion" type="xs:string" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="materia" type="xs:string" default="Java">
        <xs:simpleType>
          <xs:restricion base="xs:string">
            <xs:enumeration value="XML"/>
            <xs:enumeration value="Java"/>
          </xs:restricion>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="Separacion">
    <xs:complexType/>
  </xs:element>
</xs:schema>

=== SanchezMarioo/1-DAM/Lenguajes de Marcas/XML/XSD/Ejer10.xml
<?xml version="1.0" encoding="UTF-8"?>

<Libro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/C:/1-DAM/Lenguajes%20de%20Marcas/XML/XSD/Ejer10.xsd">
  <Titulo>Pepe</Titulo>
  <Contenido>
    <Capitulo materia="XML">
      <Tema>Ficcion</Tema>
      <Seccion apartados="si">Secion II</Seccion>
    </Capitulo>
        <Capitulo>
        <Tema>Otro tema</Tema>
        <Seccion apartados="no">Seccion III</Seccion>
      </Capitulo>
    <Separacion></Separacion>
  </Contenido>
  <Copyright>ASVDS</Copyright>
</Libro>
